social_id: 
  default: ""
  description: 
    en: Social provider name
  
social_icon: 
  default: ""
  description: 
    en: Social provider icon. Choose a <a href="https://fontawesome.com/v4.7.0/icons/">Fontawesome icon</a> 
    
social_title: 
  default: ""
  description: 
    en: Text that appears when you move the mouse over the button    
  
social_link: 
  default: ""
  description: 
    en: This is your social link  
